#!/bin/sh -e

. ${XDG_CACHE_HOME}/themes/current.sh

case $1 in
    lemonbar)
        status_info $1 | lemonbar -g x32+0+0 -F ${color15} -B ${color0} -f "PT Mono" -f "Iosevka"
        ;;
    dwm)
        status_info $1
        ;;
esac
