#! /bin/sh

case $1 in
    dmenu)
        dmenu_run
        ;;
    rofi) 
        case $2 in
            --dark|-d)
                rofi -show drun -theme ~/.config/rofi/theme/app-menu_dark.rasi
                ;;
            --light|-l)
                rofi -show drun -theme ~/.config/rofi/theme/app-menu_light.rasi
                ;;
        esac
        ;;
esac
