#!/usr/bin/env bash

usage() { 
    >&1 echo 'usage: volume [-i] [-d] [-s] [-t]' ;
    >&2 echo 'usage: volume [-i] [-d] [-s]' ;
    exit 1 ;
}

inc() {
    pamixer --sink 0 -i $1 ;
}

dec() {
    pamixer --sink 0 -d $1 ;
}

toggle() {
    pamixer --sink 0 -t ;
}

get() {
    pamixer --sink 0 --get-volume ;
}

_set() {
    if [ "$1" -gt 100 ] ; then
        set 100
    elif [ "$1" -lt 0 ] ; then
        set 0
    fi

    set -- $(echo "$1" | bc)
    [ "${1%%.*}" -gt 100 ] && set 100
    pamixer --sink 0 --set-volume $1 ;
}

case "$1" in
    inc|-i) inc  "$2" ;;
    dec|-d) dec  "$2" ;;
    set|-s) _set "$2" ;;
    toggle|-t) toggle ;;
    -h) usage ;;
     *) get
esac
