#! /bin/sh

get_bat() {
    read -r p </sys/class/power_supply/BAT0/capacity
    read -r s </sys/class/power_supply/AC/online
    case $s in
        1) e=' ' ;;
        0) case ${p%?} in
               [8-9]|10) e='' ;;
               [7-8]) e='' ;;
               [6-7]) e='' ;;
               [5-6]) e='' ;;
               [4-5]) e='' ;;
               [3-4]) e='' ;;
               [2-3]) e='' ;;
               [1-2]) e='' ;;
               [0-1]) e='' ;;
                   *) e=''
           esac
    esac
    printf "$e %s%%\n" "$p"
}

main() {
    get_bat
}

main "$@"
