#! /bin/sh

get_bat() {
    read -r p </sys/class/power_supply/BAT0/capacity
    read -r s </sys/class/power_supply/AC/online
    case $s in
        1) e=' ' ;;
        0) case ${p%?} in
               [9-1]|10) 
                   e='' ;;
               [8-9]|10) 
                   e='' ;;
               [7-8]|10) 
                   e='' ;;
               [6-7]|10) 
                   e='' ;;
               [5-6]|10) 
                   e='' ;;
               [4-5]|10) 
                   e='' ;;
               [3-4]|10) 
                   e='' ;;
               [2-3]|10) 
                   e='' ;;
               [1-2]|10) 
                   e='' ;;
               *) 
                   e=''
                   ;;
           esac
    esac

    printf '%s\n' "$e $p%"  
}

main() {
    get_bat
}

main "$@"
