#!/bin/sh -e

inc() {
    xbacklight -inc "$1"
}

dec() {
    xbacklight -dec "$1"
}

_set() {
    xbacklight -set "$1"
}

get() {
    printf "%.0f%%\n" $(xbacklight -get)
}


main() {
    flag="$1"
    case $flag in
        --inc|-i)
            shift
            inc "$1" ;;
        --dec|-d)
            shift
            dec "$1" ;;
        --set|-s)
            shift
            _set "$1" ;;
        --get|-g)
            get ;;
        *)
            get ;;
    esac
}

main "$@"
