#! /bin/sh

inc() {
    xbacklight -inc "$1"
}

dec() {
    cur_bright=$(get)
    if [ $cur_bright = "1%" ] ;  then
        break;
    elif [ $cur_bright-$1 < 0 ] ;  then
        $(_set 1)
    else
        xbacklight -dec "$1"
    fi
}

_set() {
    xbacklight -set "$1"
}

get() {
    printf "%.0f%%\n" $(xbacklight -get)
}

case "$1" in
    --inc|-i)
        inc "$2" ;;
    --dec|-d)
        dec "$2" ;;
    --set|-s)
        _set "$2"
        ;;
    --get|-g)
        get ;;
    *)
        get ;;
esac
