#! /bin/sh

inc() {
    xbacklight -inc "$1"
}

dec() {
    cur_bright=$(get)
    if [ $cur_bright = "1" ] ;  then
        break;
    elif [ $cur_bright-$1 -le 1 ] ;  then
        $(_set 1)
    else
        xbacklight -dec "$1"
    fi
}

_set() {
    xbacklight -set "$1"
}

get() {
    case $1 in
        --human|-h)
            printf "%.0f%%\n" $(xbacklight -get)
            ;;
        *)
            printf "%.0f\n" $(xbacklight -get)
            ;;
    esac
}


case "$1" in
    --inc|-i)
        inc "$2" ;;
    --dec|-d)
        dec "$2" ;;
    --set|-s)
        _set "$2"
        ;;
    --get|-g)
        get "$2" ;;
    *)
        get -h;;
esac
