#! /bin/sh

usage() {
    >&2 echo 'usage: volume [-i value] [-d value] [-s value] [-t]' ;
    exit 1 ;
}

inc() {
    amixer sset Master $1+
}

dec() {
    amixer sset Master $1-
}

toggle() {
    amixer sset Master toggle
}

get() {
    amixer sget Master $1
}

mute() {
    amixer sset Master mute
}

_set() {
    amixer sset Master $1
}

main() {
    case "$1" in
        --inc|-i) inc  "$2" ;;
        --dec|-d) dec  "$2" ;;
        --set|-s) _set "$2" ;;
        --mute|-m) mute "$2" ;;
        --toggle|-t) toggle ;;
        --help|-h) usage ;;
        *) get
    esac
}

main "$@"
