#! /bin/sh

lock() {
    case $1 in
        -slock)
            slock
            ;;
        -i3lock)
            i3lock
            ;;
        -betterscreenlocker)
            ;;
    esac
}

lock "$@"
