#!/bin/sh

#
# http://github.com/vitax
#
# Script to help handle multihead scenarious for mobile workstations
#

set -e

MAIN_SCREEN="eDP1"

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [ --connect | -c] <device> or [ --auto | -a ]" 
    >&2 printf '\t\t\t %s\n' "[ --disconnect | -d ]"
    >&2 printf '\t\t\t %s\n' "[ --left | -l ] [ --right | -r ] [ --above | -a] [--below | -b ] "
    exit
}

connect() {
    ouput_screen=$1
    direction=$2
    xrandr --output $ouput_screen "$direction" "$MAIN_SCREEN" --auto
}

disconnect() {
    xrandr --output $1 --off
}

set_wallpaper() {
    [ -f ${HOME}/.fehbg ] || sh ${HOME}/.fehbg
}

main() {
    case $1 in
        --connect|-c)
            case $2 in
                HDMI[0-9])
                    case $3 in
                        --above|-a)
                            connect $2 --above ;
                            set_wallpaper
                            ;;
                        --below|-b)
                            connect $2 --below ;
                            set_wallpaper
                            ;;
                        --left|-l)
                            connect $2 --left-of ;
                            set_wallpaper
                            ;;
                        --right|-r)
                            connect $2 --right-of ;
                            set_wallpaper
                            ;;
                        *)
                            usage
                            ;;
                    esac
                    ;;
                DP[0-9])
                    case $3 in
                        --above|-a)
                            connect $2 --above ;
                            set_wallpaper
                            ;;
                        --below|-b)
                            connect $2 --below ;
                            set_wallpaper
                            ;;
                        --left|-l)
                            connect $2 --left-of ;
                            set_wallpaper
                            ;;
                        --right|-r)
                            connect $2 --right-of ;
                            set_wallpaper
                            ;;
                        *)
                            usage
                            ;;
                    esac
                    ;;
                *)
                    usage
                    ;;
            esac
            ;;
        --disconnect|-d)
            case $2 in
                HDMI-[0-9])
                    disconnect $2
                    ;;
                DP[0-9])
                    disconnect $2
                    ;;
                *)
                    usage
                    ;;
            esac
            ;;
        --auto|-a)
            xrandr --auto
            ;;
        --help|-h)
            usage
            ;;
        *)
            usage
            ;;
    esac
}

main "$@"
