#!/bin/sh -e

#
# http://github.com/vitax
#
# Script to help handle multihead scenarious for mobile workstations
#

MAIN_SCREEN="eDP1"

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [ --connect | -c] <device> or [ --auto | -a ]"
    >&2 printf '\t\t\t %s\n' "[ --disconnect | -d ]"
    >&2 printf '\t\t\t %s\n' "[ --left | -l ] [ --right | -r ] [ --above | -a] [--below | -b ] "
    exit
}

connect() {
    ouput_screen=$1
    direction=$(get_direction $2)
    xrandr --output $ouput_screen $direction $MAIN_SCREEN --auto
}

disconnect() {
    xrandr --output $1 --off
}

get_direction() {
    direction="$1"
    case $direction in
        --above|-a)
            printf '%s' "--above"
            ;;
        --below|-b)
            printf '%s' "--below"
            ;;
        --left|-l)
            printf '%s' "--left-of"
            ;;
        --right|-r)
            printf '%s' "--right-of"
            ;;
    esac
}

main() {
    flag="$1"
    shift
    case $flag in
        --connect|-c)
            connect $1 $2
            ;;
        --disconnect|-d)
            disconnect $1
            ;;
        --auto|-a)
            xrandr --auto
            ;;
        --help|-h)
            usage
            ;;
    esac
}

main "$@"
