#! /bin/sh

usage() { 
    >&2 echo 'usage: volume [-i value] [-d value] [-s value] [-t]' ;
    exit 1 ;
}

inc() {
    pamixer --sink 0 -i $1
}

dec() {
    pamixer --sink 0 -d $1
}

toggle() {
    pamixer --sink 0 -t
}

get() {
    pamixer --sink 0 --get-volume-human
}

_set() {
    if [ "$1" -gt 100 ] ; then
        set 100
    elif [ "$1" -lt 0 ] ; then
        set 0
    fi

    pamixer --sink 0 --set-volume $1
}

case "$1" in
    --inc|-i) inc  "$2" ;;
    --dec|-d) dec  "$2" ;;
    --set|-s) _set "$2" ;;
    --toggle|-t) toggle ;;
    --help|-h) usage ;;
     *) get
esac
