#! /bin/sh

usage() { 
    >&2 echo 'usage: volume [-i value] [-d value] [-s value] [-t]' ;
    exit 1 ;
}

inc() {
   amixer sset Master $1+ ; 
}

dec() {
    amixer sset Master $1- ;
}

toggle() {
    amixer sset Master toggle ;
}

get() {
    amixer sget Master | grep 'Mono:' | awk -F'[][]' '{ print $2 }';
}

_set() {
    if [ "$1" -gt 100 ] ; then
        set 100
    elif [ "$1" -lt 0 ] ; then
        set 0
    fi

    set -- $(echo "$1" | bc)
    [ "${1%%.*}" -gt 100 ] && set 100
    amixer sset Master $1 $1 ;
}

case "$1" in
    --inc|-i) inc  "$2" ;;
    --dec|-d) dec  "$2" ;;
    --set|-s) _set "$2" ;;
    --toggle|-t) toggle ;;
    --help|-h) usage ;;
     *) get
esac
