#! /bin/sh -e

launch_rofi() {
    rofi -show drun "$@"
}

launch_dmenu() {
    dmenu_run "$@"
}

main() {
    if [ ! -z "$1" ]; then
        flag="$1"
        shift
    else
        return
    fi

    case $flag in
        dmenu)
            launch_dmenu "$@"
            ;;
        rofi)
            launch_rofi "$@"
            ;;
    esac
}

main "$@"
