#! /bin/sh

case $1 in
    dmenu)
        dmenu_run -p " " -h 36 -w 1420 -y 40 -x 250
        ;;
    rofi) 
        case $2 in
            -t)
                rofi -show drun -theme $3
                ;;
            *) 
                rofi -show drun
        esac
esac
