#! /bin/sh

case $1 in
    dmenu)
        dmenu_run -p " " -h 36 -w 1420 -y 40 -x 250
        ;;
    rofi) 
        case $2 in
            --dark|-d)
                rofi -show drun -theme ~/.config/rofi/theme/app-menu_dark.rasi
                ;;
            --light|-l)
                rofi -show drun -theme ~/.config/rofi/theme/app-menu_light.rasi
                ;;
        esac
        ;;
esac
