#!/bin/sh
#
# http://github.com/vitax
#
# Display traffic
#

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} []"
    exit 1
}

get_interface() {
    while read -r int _ ; do
        case $int in
            Inter*|*face)
                # discard
                ;;
            *)
                printf '%s\n' "${int%:}"
        esac
    done </proc/net/wireless
}


get_traffic() {
    int=$(get_interface)
    if [ -f "/sys/class/net/$int/statistics/rx_bytes" ] ; then
        read -r rx <"/sys/class/net/$int/statistics/rx_bytes"
        read -r tx <"/sys/class/net/$int/statistics/tx_bytes"
    fi
    printf 'ﲔ  %s ﲗ  %s\n' \
        "$(printf '%s' "${rx:-0}" | human)" \
        "$(printf '%s' "${tx:-0}" | human)"
}

main() {
    get_traffic
}

main "$@"
