#! /bin/sh
#
# http://github.com/Vitax
#
# Script to manage wifi connectivity
#

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [--scan|-s, --connect|-c <wpa_file>, --disconnect|-d]"
    exit 1
}

_scan() {
    sudo iwlist wlan0 scan | grep "ESSID:" | less ;
}

_connect() {
    sudo wpa_supplicant -B -i wlan0 -c $1 -D nl80211
    sudo udhcpc -i wlan0
}

_disconnect() {
    sudo pkill udhcpc
    sudo pkill wpa_supplicant
}

case "$1" in
    --scan|-s)
        _scan ;;
    --connect|-c)
        _disconnect ; _connect $2 ;
        ;;
    --disconnect|-d)
        _disconnect ;;
    *)
        usage
        ;;
esac
