#! /bin/sh
#
# http://github.com/Vitax
#
# Script to manage wifi connectivity
#

usage() {
    >&2 printf '%s\n' "Usage: ${0##*/} [--scan|-s, --connect|-c <wpa_file>, --disconnect|-d]"
    exit 1
}

_scan() {
    sudo ifconfig wlan0 scan ;
}

_connect() {
    wlp=$(ip addr | grep wlp | cut -d ' ' -f2)
    sudo wpa_supplicant -B -i $wlp -c $1
    sudo dhcpcd -i $wlp
}

_disconnect() {
    sudo pkill -9 wpa_supplicant
    sudo pkill -9 dhcpcd
}

case "$1" in
    --scan|-s)
        _scan ;;
    --connect|-c)
        _disconnect ; _connect $2 ;
        ;;
    --disconnect|-d)
        _disconnect ;;
    *)
        usage
        ;;
esac
